// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMpOOSo0MI5Aj6qQYUZRu0mW3edcSdHs',
    appId: '1:824271605986:web:c85ff01ce5a25c379c0ebb',
    messagingSenderId: '824271605986',
    projectId: 'multi-appbarber',
    authDomain: 'multi-appbarber.firebaseapp.com',
    storageBucket: 'multi-appbarber.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAWdX9KgfrKyR8DCTc0Dw_PMrI9y1bNiI',
    appId: '1:824271605986:android:bd01bbf2aef057f89c0ebb',
    messagingSenderId: '824271605986',
    projectId: 'multi-appbarber',
    storageBucket: 'multi-appbarber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNxtgxoP9bxGhaIVxux7DcRbEX2RVwxBo',
    appId: '1:824271605986:ios:d815bfcbb035462d9c0ebb',
    messagingSenderId: '824271605986',
    projectId: 'multi-appbarber',
    storageBucket: 'multi-appbarber.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNxtgxoP9bxGhaIVxux7DcRbEX2RVwxBo',
    appId: '1:824271605986:ios:d815bfcbb035462d9c0ebb',
    messagingSenderId: '824271605986',
    projectId: 'multi-appbarber',
    storageBucket: 'multi-appbarber.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnMpOOSo0MI5Aj6qQYUZRu0mW3edcSdHs',
    appId: '1:824271605986:web:b48e2c32bb50ca479c0ebb',
    messagingSenderId: '824271605986',
    projectId: 'multi-appbarber',
    authDomain: 'multi-appbarber.firebaseapp.com',
    storageBucket: 'multi-appbarber.firebasestorage.app',
  );
}
